language: java
jdk:
- oraclejdk8
script:
- mvn verify -B
notifications:
  slack:
    secure: OOjL1XVxCeCq69yBvsjEcUzHzAhUD67D7IQ/B0VXg+QAPI2TBiZ8A5FzlcyvM7D0RbI2EZT9yLrkFufKJVsRqF6uXfb54SOv9JTxx1Q4uQ432Ks/TFdcwxSBFOeAR/LCI3nfiEfGXmA3FD9KCb1DYU03JehfEYCCJDP3O6Cf+elQm/X2ouvU4WqBLBT87KMnwactLNcbXFqJc1rUac4G+Hss6tUZ+j7G8GHRu3Xz+pDXsP3H+d99qWT/JfpzQoFN6G7u2C2aY9n4qYiZqIKMCx+qTSZVp7UMIm1j6lvh4CsrNC0GaG7AMA37FvyIJ9c22RB2fGSqWLCr3fWCW6TFbyAqNuSXisT9XZWbnWct/Owcy6iklLMWk0rJSQQHYQokoZgh6a8WWk9pdppLegFBUG2yOMOQOe/Oo/lqPZ7TN2kWsemnWEYAM34KxM6v9vVxIhQKrRQHZYRrlZntZBEq+fRzM4fMrYC0U+oDKkG9uR/ib9oGKws/7Ccds1Kj43vVUJZZkodsKFDUvdchAP+t/uOJfyECSnLPWkk6d0a2fzwrHuUTmjHu3V5sBBlRcsKPOhbF8GPKBcBaBUhSfRvqnW0gNaDOSrrL9yjuE2NQxHgV6v5SXQLS6ZpXGyOdrulwPDb58PM5EWlmnlZ+xdoTmby5Z4o67EaT5c8oNyXDi1k=
